apiVersion: v1
kind: Service
metadata:
  name: aws-load-balancer-webhook-service
  namespace: kube-system
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 443
    targetPort: 443
  selector:
    app: aws-load-balancer-webhook

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-webhook
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-load-balancer-webhook
  template:
    metadata:
      labels:
        app: aws-load-balancer-webhook
    spec:
      containers:
      - name: aws-load-balancer-webhook
        image: amazon/aws-alb-ingress-controller:v2.3.0
        args:
        - --secure-port=443